### ISSUE TITLE
Make certain routes scroll to the top

### ISSUE THREAD

**Issue by trevorsee** [OOKB/mgs2018#9]
**Should start at top:**
- details: '/details/:showId'
- me: '/me(/:artId)'
- studentDetail: '/students/:studentId'

**Should not:**
- home: '/home'
- studentList: '/students'

**Comment by webmasterkai** [comment]
Let me know if you find anything else that needs fixing. If you add the `top` property to a `<Link />` invocation it should work as expected. The window action is happening on the individual link click instead of on the route but the results should be as you would expected. On the route is tricky because typical forward/back browser buttons usually restores page position and always going to the top on the route visit would override that functionality.
